"""empty message

Revision ID: 98d39ecbec30
Revises: 
Create Date: 2022-11-21 08:27:16.173589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d39ecbec30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BIGINT(), nullable=False),
    sa.Column('category_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('profile_picture', sa.TEXT(), nullable=True),
    sa.Column('hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('product',
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('product_name', sa.TEXT(), nullable=True),
    sa.Column('picture', sa.TEXT(), nullable=True),
    sa.Column('selling_price', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('available', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=True),
    sa.Column('create_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('product')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
