"""empty message

Revision ID: cbf034927eb9
Revises: 98d39ecbec30
Create Date: 2022-11-21 08:40:11.930469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbf034927eb9'
down_revision = '98d39ecbec30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=100),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
